Repository cs130-w22/Group-A7, pull requests merged in 2022-03, with the labels that each got.

#24 Faraz/scraper
  backend/database/maketables.sql
  backend/scraper/main.py
Labels: epic

#41 Scraper class
  backend/scraper/main.py
  backend/scraper/scraper_tests.py
Labels: epic, story

#59 fixed time url bug and increased test coverage
  backend/scraper/main.py
  backend/scraper/scraper_tests.py
Labels: bug, story
